// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMwmclwcaL_kVUqbYM8cB9fE_YWrxupks',
    appId: '1:530949211062:web:bedd1d154c83b390857717',
    messagingSenderId: '530949211062',
    projectId: 'stylesphere-a0c0d',
    authDomain: 'stylesphere-a0c0d.firebaseapp.com',
    storageBucket: 'stylesphere-a0c0d.firebasestorage.app',
    measurementId: 'G-MJTLH67FS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVhmDrpsKQRRlMHmdiW0f-pNLrtNKtGjE',
    appId: '1:530949211062:android:5b812dcf016846f8857717',
    messagingSenderId: '530949211062',
    projectId: 'stylesphere-a0c0d',
    storageBucket: 'stylesphere-a0c0d.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMwmclwcaL_kVUqbYM8cB9fE_YWrxupks',
    appId: '1:530949211062:web:fb558ee643982b39857717',
    messagingSenderId: '530949211062',
    projectId: 'stylesphere-a0c0d',
    authDomain: 'stylesphere-a0c0d.firebaseapp.com',
    storageBucket: 'stylesphere-a0c0d.firebasestorage.app',
    measurementId: 'G-CYQFEQ74QX',
  );
}
